### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by hacklschorsch** [PrivateStorageio/PrivateStorageDesktop#17]
This is open source all right, but without a license, one can't know what they are allowed to do with the source (and assets!).

I propose adding a `LICENSE` or `LICENSE.txt` file clarifying the situation.

**Comment by crwood** [comment]
Thanks for flagging this. Since we're beholden to PyQt5's GPLv3 license, I would assume that the scripts in this repo that are used to build the resultant (GPLv3) application should probably also be GPLv3. I have no idea, however, about licensing/restrictions for the image files/assets. I will (try to) find out...

**Comment by hacklschorsch** [comment]
According to https://www.qt.io/faq/tag/introduction there's also a LGPL3 option since Qt 5.7?

**Comment by crwood** [comment]
Qt5 and PyQt5 are different things though; I'm referring to PyQt5 (which is GPLv3 -- and which would thereby require any application depending on it to also be GPLv3 or later).

**Comment by hacklschorsch** [comment]
> Qt5 and PyQt5 are different things though

Right!  Thank you.  I wrongly assumed (1) PyQt would be the official Python bindings and (2) as such have the same license.
The first assumption is wrong - that would be PySide ([2 for Qt5](https://pypi.org/project/PySide2/) and [5 for Qt6](https://pypi.org/project/PySide6/)).
Should we ever have a really good reason we could probably switch to PySide, but until that, the code must be licensed under GPLv3.

**Comment by hacklschorsch** [comment]
These links make it look like the icons and other such assets don't have to be GPL'd:

https://opensource.stackexchange.com/a/12620
> [Section 7 (especially 7.e) of GPLv3](https://www.gnu.org/licenses/gpl-3.0-standalone.html#section7) provides the basis for what you want to do, as it allows the limitation of rights for trademarks and logos. It will be difficult to argue that for all graphics/images in the app, or even for the color scheme, but where a trademark/logo can be reasonably assumed you can restrict the use.

Or, of course, use *another* indirection (this is from the same SO answer):

> Another approach: You could distribute the app in a container where the GPL-ed code is separate from the graphics, and the image files are distributed under a different license (for example a Creative Commons or proprietary license).


https://softwareengineering.stackexchange.com/a/155276

> [Section 7 of GPLv3](https://www.gnu.org/licenses/gpl-3.0-standalone.html#section7) states:
>
>> Notwithstanding any other provision of this License, for material you add to a covered work, you may (if authorized by the copyright holders of that material) supplement the terms of this License with terms: ... c. Prohibiting misrepresentation of the origin of that material, or requiring that modified versions of such material be marked in reasonable ways as different from the original version

**Comment by crwood** [comment]
>Should we ever have a really good reason we could probably switch to PySide, but until that, the code must be licensed under GPLv3.

Even in that case, however, we still depend on other GPL-licensed software (Tahoe-LAFS, Magic-Folder).

Anyway, I think we should add a GPL(v3) license file to this repo for now and inquire further/elsewhere about the trademark/logo. Thoughts?

**Comment by hacklschorsch** [comment]
Yes, good thinking.
I would exempt our logo and name though, to avoid misrepresentation.
Please see [my review comment here](https://github.com/PrivateStorageio/PrivateStorageDesktop/pull/18#pullrequestreview-1011892989).

**Comment by exarkun** [comment]
> Thanks for flagging this. Since we're beholden to PyQt5's GPLv3 license, I would assume that the scripts in this repo that are used to build the resultant (GPLv3) application should probably also be GPLv3. I have no idea, however, about licensing/restrictions for the image files/assets. I will (try to) find out...

For what it is worth, it is not the case that we must use GPLv3 just because Qt is GPLv3.  We can use any GPLv3-compatible license.  The FSF conveniently maintains a list of such licenses - https://gplv3.fsf.org/wiki/index.php/Compatible_licenses#GPLv3-compatible_licenses (all one of them).

**Comment by exarkun** [comment]
This repository seems to be almost *entirely* assets.  There are a couple files that amount to Makefiles and total perhaps 30 lines.  I _suppose_ that is software that could be licensed.  Is that what we're talking about here - `Makefile` and `make.bat`?  Everything else would be excluded by the exception being discussed.

Separately, I don't see a requirement to use GPLv3 here.  GPLv3 is compatible with at least Apache v2.  And the software in this repository doesn't link anything, it just moves files around so I'm not sure we even have to choose a GPLv3-compatible license anyway.

**Comment by hacklschorsch** [comment]
Thanks JP, good points.

> Is that what we're talking about here - Makefile and make.bat? 

I was mostly concerned with the fact that we distribute binaries with installers etc - for our modified GridSync - and those should bear a license.

> Separately, I don't see a requirement to use GPLv3 here.

I believe we must use GPLv3 since [GridSync is GPLv3](https://github.com/gridsync/gridsync/blob/master/LICENSE) and what we build is a modified version of that.

I don't see how this repo would fall under ["mere aggregation" (GPL2)](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html#section2) or ["aggregates" clause (GPLv3)](https://www.gnu.org/licenses/gpl-3.0.html#section5), but I might be wrong.

Or maybe another reason I don't see yet?

**Comment by meejah** [comment]
This repo doesn't contain any Gridsync code I think is the point (in fact, it hardly contains any code at all).

**Comment by exarkun** [comment]
@meejah got part of my point.  Put another way, PrivateStorageDesktop is not itself a derivative work of GridSync.  It does a bunch of stuff with GridSync but it is an independent and novel work of its own.

It *builds* something that is certainly a derivative work of GridSync.

So I don't think the contents of PrivateStorageDesktop itself are required to be licensed under GPLv3.  However, the artifact it builds certainly is required to be licensed under GPLv3.

Of course, I am not a lawyer, etc.

Also, after writing my comment above, I realized that all of the end-to-end testing work we have been sketching out is in the PrivateStorageDesktop repository and some of that might invalidate some of the premises the above is based on.

Maybe this doesn't really matter very much in the end.  I have a slight resistance to making more GPLv3-licensed software because I don't fully understand the benefits of GPLv3 (as compared to, say, Apache v2).  I'd be happy to read some material on this subject if anyone wants to share it.

**Comment by hacklschorsch** [comment]
> PrivateStorageDesktop is not itself a derivative work of GridSync.

Is that really so.

> So I don't think the contents of PrivateStorageDesktop itself are required to be licensed under GPLv3. However, the artifact it builds certainly is required to be licensed under GPLv3.

What would then be the upsides of using a different license for this repository?

**Comment by exarkun** [comment]
> What would then be the upsides of using a different license for this repository?

Philosophically, not creating more software burdened with useless licensing terms (if GPLv3 is indeed useless, which as I said above I am uncertain of).

Concretely, not having to wonder if a future repository that somehow interacts with PrivateStorageDesktop also needs to be GPLv3 or not. :slightly_smiling_face:

**Comment by crwood** [comment]
Addressed by https://github.com/PrivateStorageio/PrivateStorageDesktop/pull/29
